name: ml_env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - accelerate
  - altair
  - black
  - bokeh
  - catboost
  - flake8
  - ipykernel
  - ipywidgets
  - jupyterlab
  - keras
  - lightgbm
  - matplotlib
  - modin
  - mamba
  - nltk
  - notebook
  - numpy
  - optuna
  - pandas
  - pip
  - plotly
  - polars
  - pytest
  - pynvml
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - statsmodels
  - sympy
  - tensorflow
  - torchaudio
  - torchvision
  - tqdm
  - transformers
  - xgboost
  - optimum
  - pip:
    - bitsandbytes
    - math-verify[antlr4_13_2]
    - dotenv