#to check if 32B is generating

#data 
dataset_name: "openai/gsm8k"
num_samples: 4
batch_size: 4
num_completions: 1


#model
model_name: "Qwen/Qwen2.5-32B-Instruct"
quantization: 8

#workflow 
start_token_budget: 7 #log2
end_token_budget: 10 #log2

#SAVE
SAVE_BOOL: True

#inference
inference_engine: "vllm"
max_new_tokens_frac: 0.25
vllm_gpu_memory_utilization: 0.6

#scoring 
normalise_over_solution_set: False
solution_set_batch_size: 20

#debug
DEBUG_MODE: False