#data 
dataset_name: ProCreations/SimpleMath

#workflow scale parameters
num_samples:  4
sample_idxs_range: None
batch_size: 4
num_completions: 1
force_end_batch_size: None
solution_set_batch_size: 10
ATTENTION_TYPE: flash
force_continue_repetition_threshold: 100

vllm_gpu_memory_utilization: 0.60
max_model_len: None #sets to last token budget size + buffer

#model
#model_name: microsoft/Phi-4-reasoning-plus
model_name: microsoft/Phi-4-reasoning-plus
quantization: 8 #defaults to fp16

#workflow 
start_token_budget: 9 #log2
end_token_budget: 9 #log2

#SAVE
SAVE_BOOL: False
TIME_BASED_SAVING: True
save_every_n_mins: 1

#inference
inference_engine: vllm
max_new_tokens_frac: 0.125

#scoring 
normalise_over_solution_set: False

#debug
DEBUG_MODE: True
