#data 
dataset_name: Idavidrein/gpqa

#workflow scale parameters
num_samples: 8
batch_size: 4
num_completions: 2
solution_set_batch_size: 20
vllm_gpu_memory_utilization: 0.8
max_model_len: None #sets to last token budget size + buffer

#model
model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
quantization: 8 #defaults to fp16

#workflow 
start_token_budget: 7 #log2
end_token_budget: 8 #log2

#SAVE
SAVE_BOOL: False
TIME_BASED_SAVING: True
save_every_n_mins: 30

#inference
inference_engine: "vllm"
max_new_tokens_frac: 0.0625

#scoring 
normalise_over_solution_set: True

#debug
DEBUG_MODE: False
