# -----------------------------------------------------------------------------
# Dataset & Model
# -----------------------------------------------------------------------------
dataset_name:  Idavidrein/gpqa
model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
quantization: 8  # bit precision (defaults to fp16 if not set)

# -----------------------------------------------------------------------------
# Number of samples and completions
# -----------------------------------------------------------------------------
num_samples: 1
sample_idxs_range: None  # null for full dataset
num_completions: 1

# -----------------------------------------------------------------------------
# Batch Processing
# -----------------------------------------------------------------------------
batch_size: 4
force_end_batch_size: None  # batch size for force ending generation
solution_set_batch_size: 10 # batch size for normalising over solution set (only applicable to AIMEs)

# -----------------------------------------------------------------------------
# Token Budget (log2 scale)
# -----------------------------------------------------------------------------
start_token_budget: 7  # 2^7 = 128 tokens
end_token_budget: 7    # 2^8 = 256 tokens

# -----------------------------------------------------------------------------
# vLLM configuration Settings
# -----------------------------------------------------------------------------
inference_engine: vllm #alternatively, "hf" for HuggingFace inference engine
max_new_tokens_frac: 0.125  # fraction of budget for generation
ATTENTION_TYPE: flash
vllm_gpu_memory_utilization: 0.80
max_model_len: None  # auto-set to last token budget + buffer


# -----------------------------------------------------------------------------
# Scoring Configuration
# -----------------------------------------------------------------------------
normalise_over_solution_set: True 

# -----------------------------------------------------------------------------
# Saving & Checkpointing (saves to ./results_data/run_name)
# -----------------------------------------------------------------------------
SAVE_BOOL: True
TIME_BASED_SAVING: False #if false, saves after each token budget
save_every_n_mins: 1 #save every n minutes

# -----------------------------------------------------------------------------
# Debug Options
# -----------------------------------------------------------------------------
DEBUG_MODE: False